#
# Warning! This file has been generated by the BlackBerry Java Development environment.
# Do not modify by hand.
#

all: \
     C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod \


clean:
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug > nul

rebuild: clean all

Private: \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod \


Private_files:
	@echo C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp


Debug: \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod \


Debug_files:
	@echo C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp


Release: \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod \


Release_files:
	@echo C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp


HomeIslandManager_sources = \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\DBCT.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandApplicationResource.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\IslandGui.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandProcessorEngine.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandResource.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandResourceManager.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandServiceEngine.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandSoftwareEngine.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandSubscriptionResource.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgent.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentGLOBUS.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentGNUTELLA.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentHADOOP.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentHTTP.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentJXTA.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentPGRID.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelAgentYATTA.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandTravelManager.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\islandUserResource.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\MEM.java \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\MMU.java \
    C:\open\Java\kxml2-2.3.0\src\org\kxml2\io\KXmlParser.java \
    C:\open\Java\kxml2-2.3.0\src\org\kxml2\io\KXmlSerializer.java \
    C:\open\Java\kxml2-2.3.0\src\org\kxml2\kdom\Document.java \
    C:\open\Java\kxml2-2.3.0\src\org\kxml2\kdom\Element.java \
    C:\open\Java\kxml2-2.3.0\src\org\kxml2\kdom\Node.java \
    C:\open\Java\xmlpull-1.1.3.4\xmlpull_1_1_3_4c\src\java\api\org\xmlpull\v1\XmlPullParser.java \
    C:\open\Java\xmlpull-1.1.3.4\xmlpull_1_1_3_4c\src\java\api\org\xmlpull\v1\XmlPullParserException.java \
    C:\open\Java\xmlpull-1.1.3.4\xmlpull_1_1_3_4c\src\java\api\org\xmlpull\v1\XmlPullParserFactory.java \
    C:\open\Java\xmlpull-1.1.3.4\xmlpull_1_1_3_4c\src\java\api\org\xmlpull\v1\XmlSerializer.java \

HomeIslandManager_dependencies = \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\HomeIslandManager.jdp \
    C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.rapc \
    "C:\Program Files\Research In Motion\BlackBerry JDE 4.2.1\lib\net_rim_api.jar" \

C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod : $(HomeIslandManager_sources) $(HomeIslandManager_dependencies)
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug erase C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug > nul
	@echo Building HomeIslandManager ...
	@"C:\Program Files\Research In Motion\BlackBerry JDE 4.2.1\bin\rapc.exe"  -quiet import="C:\Program Files\Research In Motion\BlackBerry JDE 4.2.1\lib\net_rim_api.jar" codename=C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.rapc warnkey=0x52424200;0x52435200;0x52525400 $(HomeIslandManager_sources)
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cod" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cod" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cod "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cod" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.jar" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.jar" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.jar copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.jar "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.jar" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.lst" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.lst" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.lst "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.lst" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.debug" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.debug" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.debug "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.debug" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.csl" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.csl" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.csl "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.csl" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cso" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cso" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp.cso "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp.cso" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.lst" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.lst" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.lst "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.lst" > nul
	@if exist "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.debug" erase "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.debug" > nul
	@if exist C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug copy C:\Consulting\IntelligentMapping\UniApp\homeIsland\UniApp-*.debug "C:\Program Files\Research In Motion\BlackBerry Device Simulators 4.2.1\4.2.1.68 (8800)\UniApp-*.debug" > nul


