/*
 * DemographicValueEditor.java
 *
 * Created on June 16, 2007, 10:43 AM
 */

package com.campaignlocal.targetIQ.gui;


import java.awt.event.MouseEvent;
import java.awt.Color;

import com.campaignlocal.targetIQ.main.ViewerManager;
/**
 *
 * @author  Administrator
 */
public class DemographicValueEditor extends javax.swing.JPanel {
    
    /** Creates new form DemographicValueEditor */
    public DemographicValueEditor() {
        initComponents();
    }
    
    public DemographicValueEditor(ViewerManager vMan)
    {
        this.vb = vMan;
        initComponents();
    }
    
    public void InitDemographicInfo()
    {
        try
        {
            this.jSlider1.setValue(0);
            this.jSlider2.setValue(0);
            
            Integer i1 = new Integer(this.jSlider1.getValue());
            Integer i2 = new Integer(this.jSlider2.getValue());
            
            //this.jTextField1.setText("000");
            //this.jTextField2.setText("000");
            
            this.jLabel5.setText("Status:Loading...");
            this.jLabel5.updateUI();
    
            
            this.vb.addDemographicLayer(i1.intValue(),i2.intValue());
        
            this.jLabel5.setText("Status:Done");
            this.jLabel5.updateUI();
    
        }
        catch(Exception e)
        {
            System.out.println("ERROR[setting displaying demog layer]:"+e.toString());
            e.printStackTrace();
        }
    }
    
    public void updateStatusValue(String statusText)
    {
         this.jLabel5.setText("Status:"+statusText);
         this.jLabel5.updateUI();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });

        jSlider2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider2MouseDragged(evt);
            }
        });
        jSlider2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider2MouseReleased(evt);
            }
        });

        jLabel1.setText("LI");

        jLabel2.setText("LI");

        jLabel3.setText("MI");

        jLabel4.setText("MI");

        jLabel5.setText("Ready");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSlider1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 140, Short.MAX_VALUE)
                                .add(jLabel3))
                            .add(layout.createSequentialGroup()
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 151, Short.MAX_VALUE)
                                .add(jLabel4))
                            .add(jSlider2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSlider1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(jLabel5)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
            
        try
        {
            Integer i1 = new Integer(this.jSlider1.getValue());
            Integer i2 = new Integer(this.jSlider2.getValue());
            
            this.jLabel5.setText("Status:Loading...");
            this.jLabel5.updateUI();
    
            
            //this.jTextField1.setText(i.toString());
            this.vb.addDemographicLayer(i1.intValue(),i2.intValue());
        }
        catch(Exception e)
        {
            System.out.println("ERROR[Slider1]:"+e.toString());
            e.printStackTrace();
        }
        
        this.jLabel5.setText("Status:Done");
        this.jLabel5.updateUI();
    
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jSlider2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseReleased
    
        try
        {        
                       
            Integer i1 = new Integer(this.jSlider1.getValue());
            Integer i2 = new Integer(this.jSlider2.getValue());
        
            this.jLabel5.setText("Status:Loading...");
            this.jLabel5.updateUI();
    
            //this.jTextField1.setText(i.toString());
            this.vb.addDemographicLayer(i1.intValue(),i2.intValue());
        }
        catch(Exception e)
        {
            System.out.println("ERROR[Slider2]"+e.toString());
            e.printStackTrace();
        }
        
        this.jLabel5.setText("Status:Done");
        this.jLabel5.updateUI();
    
    }//GEN-LAST:event_jSlider2MouseReleased

    private void jSlider2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider2MouseDragged
 
        int currentMouseX = evt.getX();
       //int currentMouseY = e.getY();
       //Integer i = new Integer(currentMouseX);
       
       if(this.jSlider2.getValueIsAdjusting())
       {
            Integer i = new Integer(this.jSlider2.getValue());
            //this.jTextField2.setText(i.toString());
            //this.vb.addDemographicLayer(i.intValue(),Color.RED,);
       }
    }//GEN-LAST:event_jSlider2MouseDragged

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged

        int currentMouseX = evt.getX();
       //int currentMouseY = e.getY();
       //Integer i = new Integer(currentMouseX);
       
       if(this.jSlider1.getValueIsAdjusting())
       {
            Integer i = new Integer(this.jSlider1.getValue());
            //this.jTextField1.setText(i.toString());
            //this.vb.addDemographicLayer(i.intValue(),Color.RED);
       }
       
    }//GEN-LAST:event_jSlider1MouseDragged
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
    
    public ViewerManager vb;
}
