========================================================================
    ACTIVE TEMPLATE LIBRARY : RemoteIslandManager Project Overview
========================================================================

AppWizard has created this RemoteIslandManager project for you to use as the starting point for
writing your Service (EXE).


This file contains a summary of what you will find in each of the files that
make up your project.

RemoteIslandManager.vcproj
    This is the main project file for VC++ projects generated using an Application Wizard. 
    It contains information about the version of Visual C++ that generated the file, and 
    information about the platforms, configurations, and project features selected with the
    Application Wizard.

RemoteIslandManager.idl
    This file contains the IDL definitions of the type library, the interfaces
    and co-classes defined in your project.
    This file will be processed by the MIDL compiler to generate:
        C++ interface definitions and GUID declarations (RemoteIslandManager.h)
        GUID definitions                                (RemoteIslandManager_i.c)
        A type library                                  (RemoteIslandManager.tlb)
        Marshaling code                                 (RemoteIslandManager_p.c and dlldata.c)

RemoteIslandManager.h
    This file contains the C++ interface definitions and GUID declarations of the
    items defined in RemoteIslandManager.idl. It will be regenerated by MIDL during compilation.

RemoteIslandManager.cpp
    This file contains the object map and the implementation of WinMain, ServiceMain, and
    the service management functions.

RemoteIslandManager.rc
    This is a listing of all of the Microsoft Windows resources that the
    program uses.


/////////////////////////////////////////////////////////////////////////////
Other standard files:

StdAfx.h, StdAfx.cpp
    These files are used to build a precompiled header (PCH) file
    named RemoteIslandManager.pch and a precompiled types file named StdAfx.obj.

Resource.h
    This is the standard header file that defines resource IDs.

/////////////////////////////////////////////////////////////////////////////
Proxy/stub DLL project and module definition file:

RemoteIslandManagerps.vcproj
    This file is the project file for building a proxy/stub DLL if necessary.
	The IDL file in the main project must contain at least one interface and you must 
	first compile the IDL file before building the proxy/stub DLL.	This process generates
	dlldata.c, RemoteIslandManager_i.c and RemoteIslandManager_p.c which are required
	to build the proxy/stub DLL.

RemoteIslandManagerps.def
    This module definition file provides the linker with information about the exports
    required by the proxy/stub.

/////////////////////////////////////////////////////////////////////////////
